# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true
os:
  - linux
  - osx

environment:
  global:
    WARNINGS_ARE_ERORRS: 1

before_install:
  - export DISPLAY=:99.0

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls(type = "all")'
